# ===================
# solver configuration
# ====================

# number of gpus to use, this will be ignored if we're not using multi-gpu training
num_gpus: 1
num_epochs: 1
num_samples_per_epoch: 50000

# run validation every N steps
vld_iter: 500

# checkpoints every N epochs
checkpoint_iter: 50

experiment_dir: "exp1"
checkpoint_dir: "exp1/checkpoints"

# path to pre-trained weights to initialize model with before training
pretrained_weights: null

worker_number: 1

# ============
# model config
# ============
batch_size: 100
num_classes: 10
learning_rate: 0.1
data_dims: [32, 32, 3]
weight_decay: 0.0005
